spring:
  application:
    name: eureka-Server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
server:
  port: 8080

management:
  security:
    enabled: false

